### ISSUE TITLE
Support an option to force saving

### ISSUE THREAD

**Issue by TuomasKiviaho** [skjolber/maven-cache-github-action#3]
Would it be possible to force the usage of maven agent (and save) even though the cache has been found. There might exist external factors such as modification of the workflow that would require always an extra commit of the pom.xml for instance whenever (transient) snapshot dependencies are wanted to be fetched using `--update-snapshots` or version ranges are used. Cache clearing could also be enforced in a similar manner but the effects would be only temporary (while the pre-existing `[cache clear]` would remain permanent)

These new options could be used for instance via `workflow_dispatch` inputs

**Comment by skjolber** [comment]
@TuomasKiviaho so basically add files to include in search, when determinig whether the cache is up to date? This does not sound that hard.

**Comment by TuomasKiviaho** [comment]
Exactly. 

And cache clearing could be triggered for instance via prompt if for some reason local repo gets corrupted (some plugins like [invoker](https://issues.apache.org/jira/browse/MRESOLVER-224) may do such thing). This way clearing would not leave mark to git history

**Comment by skjolber** [comment]
@TuomasKiviaho added parameter for specifying inputs in v3.1.1
