### ISSUE TITLE
Support for Maven wrapper

### ISSUE THREAD

**Issue by TuomasKiviaho** [skjolber/maven-cache-github-action#4]
https://issues.apache.org/jira/browse/MNG-5937

https://github.com/takari/maven-wrapper has the details but in general `.mvn/wrapper/maven-wrapper.properties` could be used to determine what maven distribution (`distributionUrl`) and which wrapper (`wrapperUrl`) are to be saved. The wrapper is in the repo as usual but  ~/.m2/wrapper contains the different distributions that wrapper downloads. I doubt that the agent approach would work here (takari and official maven have a bit different codebase) for distribution but I think that the wrapper is already covered. 

The shady part of distribution in the Takari version is that one would need to decipher the actual MD5 hashed directory from the distribution url so that the proper distribution would be preserved, but Apache official one doesn't have this extra directory layer anymore in their [PathAssembler.java](https://github.com/apache/maven/commit/9cc363811599fb0ab21090728a1d101e29169091) 

The Takari plugin would still be needed [until the 4.x is released](https://stackoverflow.com/questions/67724086/wrapperversion-not-supported-for-maven-3-8-1-it-must-be-at-least-4). For that matter I would not mind presence of MD5 hash directory would just be ignored.

**Comment by skjolber** [comment]
I'll rather try to add a [feature](https://issues.apache.org/jira/browse/MNG-7389) to maven itself, potentially it is reasonably simple to do so.

**Comment by yogurtearl** [comment]
Maven wrapper is now available as part of maven proper: https://maven.apache.org/wrapper/

**Comment by skjolber** [comment]
@TuomasKiviaho  @yogurtearl give v3.1.1 a go?
