### ISSUE TITLE
Replace deprecated save-state and set-output commands

### ISSUE THREAD

**Issue by TuomasKiviaho** [skjolber/maven-cache-github-action#5]
restore and save steps warn about save-state and set-output

`Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

`Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

The blog states that...

_Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error._

**Comment by TuomasKiviaho** [comment]
Please note also that Node 12 -> Node 16 is planned by Summer 2023.

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/`

**Comment by skjolber** [comment]
@TuomasKiviaho thanks for the heads up.

**Comment by rbrisuda** [comment]
Hello @TuomasKiviaho ,
we found the same problem. I fixed it here: https://github.com/skjolber/maven-cache-github-action/pull/7 
by my brief testing it works in the same way. You can test it on my repository if you want.

@skjolber It is not clear how you developed it and what should be included in PR. I only build it with node16 and attached all files in provided PR.

**Comment by skjolber** [comment]
Thanks @TuomasKiviaho, available as v2.0.

**Comment by miladjafary** [comment]
@skjolber I've used `skjolber/maven-cache-github-action@v2` but it gives me this error
```
Unable to resolve action `skjolber/maven-cache-github-action@v2`, unable to find version `v2`
```
Have not you release the version 2 yet?

**Comment by rbrisuda** [comment]
> @skjolber I've used `skjolber/maven-cache-github-action@v2` but it gives me this error
> 
> ```
> Unable to resolve action `skjolber/maven-cache-github-action@v2`, unable to find version `v2`
> ```
> 
> Have not you release the version 2 yet?

@miladjafary you should use either branch name, commit sha or tag name, so in this case **v2.0** and not **v2**
